name: hello

on: [push]

env:
  APPLICATION_NAME: app2

jobs:
  main:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v1.1.1
      - name: Lint code
        run: |
          flake8 --ignore=E501,E231 *.py
          pylint --disable=C0301 --disable=C0326 *.py
      - name: Run unit tests
        run: |
          python -m unittest --verbose --failfast
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
       

